---
global:
  writeToFile: false
  requestTimeout: 15s
  indexerConfig:
    enabled: true
    esServers: ["http://es-instance.com:9200"]
    defaultIndex: ripsaw-kube-burner
    type: elastic

jobs:
  - name: stage-1
    namespace: stage-1
    jobIterations: 1
    qps: 50
    burst: 50
    namespacedIterations: false
    podWait: false
    verifyObjects: false
    objects:
    - objectTemplate: "templates/configmap-scale/configmap.yml"
      replicas: 9000
      inputVars:
        data_length: 2000

  - name: delete-stage-1
    waitForDeletion: false
    jobType: delete
    objects:
    - kind: Namespace
      labelSelector: {kube-burner-job: stage-1}

  - name: stage-2
    namespace: stage-2
    jobIterations: 1
    qps: 70
    burst: 70
    namespacedIterations: false
    verifyObjects: false
    objects:
    - objectTemplate: "templates/configmap-scale/configmap.yml"
      replicas: 12600
      inputVars:
        data_length: 3000

  - name: delete-stage-2
    waitForDeletion: false
    jobType: delete
    objects:
    - kind: Namespace
      labelSelector: {kube-burner-job: stage-2}

  - name: stage-3
    namespace: stage-3
    jobIterations: 1
    qps: 90
    burst: 90
    namespacedIterations: false
    verifyObjects: false
    objects:
    - objectTemplate: "templates/configmap-scale/configmap.yml"
      replicas: 16200
      inputVars:
        data_length: 4000

  - name: delete-stage-3
    waitForDeletion: false
    jobType: delete
    objects:
    - kind: Namespace
      labelSelector: {kube-burner-job: stage-3}
