---
global:
  writeToFile: false
  indexerConfig:
    enabled: true
    esServers: [https://search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com]
    defaultIndex: ripsaw-kube-burner
    type: elastic
  measurements:
  - name: podLatency
    esIndex: kube-burner

jobs:
  - name: load-cluster
    # Worker nodes are m5.large by default (2CPUs). We want to deploy 25 pods per core. Each iteration deploys 5
    jobIterations: 1
    qps: 20
    burst: 20
    namespacedIterations: true
    namespace: load-cluster
    podWait: false
    waitWhenFinished: true
    objects:

    # 4 pods per namespace
    - objectTemplate: "https://raw.githubusercontent.com/rsevilla87/cluster-perf-ci/master/templates/postgres-secret.yml"
      replicas: 1

    - objectTemplate: "https://raw.githubusercontent.com/rsevilla87/cluster-perf-ci/master/templates/postgres-deployment.yml"
      replicas: 1

    - objectTemplate: "https://raw.githubusercontent.com/rsevilla87/cluster-perf-ci/master/templates/postgres-service.yml"
      replicas: 1

    - objectTemplate: "https://raw.githubusercontent.com/rsevilla87/cluster-perf-ci/master/templates/postgres-networkpolicy.yml"
      replicas: 1
      
    - objectTemplate: "https://raw.githubusercontent.com/rsevilla87/cluster-perf-ci/master/templates/app-configmap.yml"
      replicas: 1

    - objectTemplate: "https://raw.githubusercontent.com/rsevilla87/cluster-perf-ci/master/templates/app-deployment.yml"
      replicas: 1
      inputVars:
        podReplicas: 4
