kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: perfapp-{{.Replica}}
spec:
  template:
    metadata:
      labels:
        name: perfapp-{{.Replica}}
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "" 
      containers:
      - name: perfapp
        image: quay.io/rsevilla/perfapp:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: postgres-{{.Replica}}
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-{{.Replica}}
              key: password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-{{.Replica}}
              key: database
        - name: POSTGRESQL_HOSTNAME
          value: postgresql-{{.Replica}}
        - name: POSTGRESQL_PORT
          value: '5432'
        - name: POSTGRESQL_RETRY_INTERVAL
          value: '5'
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      name: perfapp-{{.Replica}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
